<exp> := <add> | <sub> | <mul> | <div> | - <exp> | <num>;
<add> := <num> + <num> | <num> + ( <exp> ) | ( <exp> ) + <num> | ( <exp> ) + ( <exp> );
<sub> := <num> - <num> | <num> - ( <exp> ) | ( <exp> ) - <num> | ( <exp> ) - ( <exp> );
<mul> := <num> * <num> | <num> * ( <exp> ) | ( <exp> ) * <num> | ( <exp> ) * ( <exp> );
<div> := <num> / <num> | <num> / ( <exp> ) | ( <exp> ) / <num> | ( <exp> ) / ( <exp> );
<num> := ^[0-9]+;